import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <header className="bg-gray-800 text-white text-center py-4 fixed top-0 w-full z-10">Header</header>
          <main className="mt-14">{children}</main>
          <footer className="bg-gray-800 text-white text-center py-4 fixed bottom-0 w-full z-10">Footer</footer>
        </div>
      </body>
    </html>
  );
}
